### PR TITLE
Restructure code for multi-page functionality

### PR DESCRIPTION
**Pull request by ishandandekar**
Changes in the code:
- Removed `app.py`
- Added **pages** directory containing all the files for pages, other than the main
- Added `Home.py`, containing the main content and navigation
- Added `.gitignore` file

Other code such as styling and content is still the same.

### CODE REVIEW

**Comment by Geeky-Sam01** [comment]
Seems good , can you attach a Screenshot or gif , to show everything is working fine?

**Comment by Geeky-Sam01** [comment]
Seems good , can you attach a Screenshot or gif , to show everything is working fine?

**Comment by ishandandekar** [comment]
image

**Comment by Geeky-Sam01** [comment]
Can you move the 'Nagivation' heading above the pages section?
<br>
  ```
Nagivation:
  Home
  About
  Contact Us
  Github
```

**Comment by ishandandekar** [comment]
I am guessing this isn't possible, I looked through the multi-page documentation and can't find anything that addresses this issue

**Comment by Geeky-Sam01** [comment]
Okay , then we'll have to find some work around later. For , now it perfect! thanks and great work! 😄✔

**Pull request merged**
